services:
  - type: web
    name: blood-pressure-monitor
    env: node
    plan: free
    buildCommand: pnpm install && pnpm run db:generate && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bp-monitor-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        value: HQoLfbRWO7sGkIQUyY7wAvDbwbCONnjG6Jd7+RYN66U=
      - key: NEXTAUTH_URL
        value: https://blood-pressure-monitor.onrender.com

databases:
  - name: bp-monitor-db
    databaseName: bp_monitor
    user: bp_user
    plan: free
